name: Docker readme update

on:
  workflow_dispatch:
  push:
    分支:
      - master
    paths:
      - README。md

jobs:
  job:
    name: Docker Hub Description
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v5

      - 
        name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v5
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: mimimimimimimiiii/wxchat
          short-description: MoviePilot 微信转发代理
          readme-filepath: ./README.md
